export const CV = {
  title: 'Software developer',
  first_name: 'Miroslav',
  last_name: 'Popugajev',
  birthdate: '1984-12-22',
  short_description: 'Senior Full-Stack Developer',
  descriptions: [
    'Started programming games with Basic at the age of 16 and quickly realized that programming was my passion which continues till this day',
    'Prefer algorithmic/scaling challenging tasks',
    'Ready to relocate, learn new technologies (change platform, programming language)',
    'Languages: English (major language in last 3 jobs), Lithuanian (most used now), Russian (native)',
    'Driving license: A, B',
  ],
  experience: [
    {
      project: 'Irektus',
      title: 'Javascript Developer',
      company: 'Fatmap',
      from: '2017 December',
      to: '2018 February',
      description: 'Port map software to support offline mode on mobile devices',
    },
    {
      title: 'Unity/WebGL Developer',
      company: 'Fatmap',
      from: '2015 October',
      to: '2017 July',
      description: 'Develop modern 3D map engine with Unity and WebGL (ThreeJS)',
      achievements: [
        'Map tracks/objects editor',
        'GPU shader programs',
        'Map data processing procedures',
        'Browser storage and caching',
      ],
    },
    {
      project: 'Irektus',
      title: 'Senior Full-Stack Developer',
      company: 'Drivr',
      from: '2015 January',
      to: '2015 April',
      description: 'Taxi platform development (Uber clone). ASP.NET MVC, Angular',
    },
    {
      title: 'Senior .NET Developer',
      company: 'Devbridge',
      from: '2014 October',
      to: '2015 January',
      description: 'Ship mission-critical software at scale, under aggressive deadlines',
      achievements: [
        'JSSI - Aircraft maintenance. Client dashboard for aircraft parts provider',
        'Grainger - Prototype for big product catalog. Product indexing and search',
        'Monotype - Fonts e-commerce platform. Apply new font rendering engine',
        'VideoBrewery - Marketplace of freelancers and studios to craft custom video content for your company',
        'Drive Safe Today - Online defensing driving courses. Create referral system',
      ],
    },
    {
      project: 'Irektus',
      title: 'ASP.NET Backend Developer',
      company: 'Tele2',
      from: '2014 August',
      to: '2014 August',
      description: 'Develop services for mass sms sending',
    },
    {
      title: 'Team lead',
      company: 'Nevda',
      from: '2013 October',
      to: '2014 April',
      description: 'Support and improve document management software',
      achievements: [
        'Migrate classic ASP project to ASP.NET MVC',
        'Delegate tasks for 6 members team',
        'Create own task management software',
        'Smart project and database installer',
      ],
    },
    {
      project: 'Irektus',
      title: 'Full-Stack Developer',
      company: 'Irektus',
      from: '2013 April',
      to: '2013 October',
      description: 'Flight search engine startup. Technologies: WPF, React',
      achievements: [
        'Continuous flight data collection from >20 airlines',
        'Fast trip search (less than second) for all non-direct flights',
        'Integrate hotel search engine (Hotelston)',
      ],
    },
    {
      title: 'Full-Stack .NET Developer',
      company: 'Draugas.lt',
      from: '2010 September',
      to: '2013 April',
      description: 'Adding new features to most profitable Lithuanian dating website',
      achievements: [
        'Astrological web portal http://fortuna.draugas.lt. Front side and CMS',
        'People compatibility analysis using data mining http://pazintys.draugas.lt/testai',
        'Facebook like chat development and embedding to existing messaging system',
        'Chat load test application (benchmark). Emulate chat user behaviour',
        '.Net distributed session and cache engine (based on Redis NoSQL database)',
        'Custom .Net binary serialization library with direct RAM access',
        // 'Pets social network http://cutester.com ',
        // 'International dating website http://pureflirt.com',
        // 'Asp.Net CMS tools for internal uses (resource manager, seo editor, error viewer)',
        // 'Desktop project management application (client for Redmine)',
      ],
    },
    {
      project: 'Irektus',
      title: 'Silverlight Developer',
      company: 'Ekskomisaru biuras',
      from: '2010 July',
      to: '2010 September',
      description: 'Applications for frontier guards. Client and server side. Silverlight, WCF, MsSql',
    },
    {
      project: 'Irektus',
      title: 'Compact .NET Developer',
      company: 'Linikodas',
      from: '2010 February',
      to: '2010 April',
      description: 'Software for handheld device used by logistic companies',
    },
    {
      project: 'Irektus',
      title: 'PHP Developer',
      company: 'Coralmap',
      from: '2009 November',
      to: '2010 February',
      description: 'Social network portal development (Spreadia). Yii framework',
    },
    {
      project: 'Irektus',
      title: 'PHP Developer',
      company: 'Corpus Integrum',
      from: '2009 August',
      to: '2009 November',
      description: 'Website for ministry of tranport http://transp.lt',
    },
    {
      project: 'Irektus',
      title: 'Flash/PHP Developer',
      company: 'Corpus Integrum',
      from: '2009 July',
      to: '2009 September',
      description: 'Fashion website update http://prettypolly.co.uk',
    },
    {
      title: '.NET Developer',
      company: 'Etalinkas',
      from: '2009 April',
      to: '2009 August',
      description: 'Debt administration software (Sergel)',
      achievements: [
        'Debt collection program improvement (.NET, DevExpress)',
        'Debt collection program WEB interface creation (ASP.NET, MS SQL)',
        'Flylal group client management system',
      ],
    },
    {
      title: '.NET Developer',
      company: 'Elgama sistemos',
      from: '2006 June',
      to: '2009 February',
      description: 'Software for custom measurement hardware',
      achievements: [
        'Database design of electrical measurement system',
        'Receiving and storing data from a variety of electricity meters',
        '"Vaisala" meteorological station website',
        'Electrical reporting system. Generates PDF reports using templates',
        'Time planning tool for reports sending and data collecting at specified time intervals',
      ],
    },
    {
      title: 'C/C++ developer',
      company: 'Ošerovskio company',
      from: '2005 July',
      to: '2006 April',
      description: 'Software for collecting data from power station reactor\'s management system from a power reactor control system. SMS sending/receiving service. QT, MySQL',
      achievements: [
        'SMS sending/receiving service using GSM modems',
        'Database data monitoring and notifications',
      ],
    },
  ],
  education: [
    { title: 'Bachelor\'s degree', company: 'Vilnius University', from: '2003', to: '2007' },
    { title: 'Master\'s degree', company: 'Vilnius University', from: '2007', to: '2008' },
  ],
  skills: [
    { name: 'C#', description: 'ASP.NET MVC, WPF, WebForms', percentage: 95 },
    { name: 'Javascript', description: 'React, Angular, ES6, NodeJS, WebGL', percentage: 92 },
    { name: 'SQL', description: 'MySQL, MSSQL, Redis, Elasticsearch', percentage: 89 },
    { name: 'Other', description: 'Python, PHP, Java, Unity, Tensorflow', percentage: 75 },
  ],
  contacts: {
    email: 'mipo3815@gmail.com',
    phone: '+370 602 00021',
    skype: 'mipo47',
    address: 'Vilnius, Lithuania',
  },
  portfolio: [
    { link: 'https://itunes.apple.com/us/app/fatmap-outdoor-map-and-guide/id934760071?mt=8', title: 'Offline 3D maps' },
    { link: 'http://maps.fatmap.com', title: '3D maps for web' },
    { link: 'https://www.grainger.com/category/electrical/ecatalog/N-bi5', title: 'Catalog search engine prototype' },
    { link: 'http://www.videobrewery.com', title: 'Marketplace of freelancers and studio' },
    { link: 'https://www.drivesafetoday.com', title: 'Online defensing driving courses' },
    { link: 'http://prettypolly.co.uk', title: 'Fashion website' },
    { link: 'https://fortuna.draugas.lt', title: 'Astrological web portal' },
  ],
  interests: null,
};
